In [1]:
import numpy as np


In [2]:
np.__version__

'1.23.4'

In [3]:
arr = np.array([1,2,3,4,5,6])
print(arr)

[1 2 3 4 5 6]


In [4]:
type(arr)

numpy.ndarray

In [9]:
# 0 D array
import numpy as np
arr = np.array([23])
print(arr)
print("\n")

[23]




In [8]:
# 1D array
arr1 = np.array([12,23,3,4,56])
print(arr1)

[12 23  3  4 56]


In [11]:
# 2D array
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [15]:
#3d array
arr3 = np.array([[[7,8,9],[1,2,3]],[[4,5,6],[1,2,3]]])
print(arr3)

[[[7 8 9]
  [1 2 3]]

 [[4 5 6]
  [1 2 3]]]


In [16]:
import numpy as np

arr = np.array([1,2,3,4])
print(arr)
print('numbers of dimensions : ',arr.ndim)

[1 2 3 4]
numbers of dimensions :  1


In [18]:
import numpy as np
arr= np.array([12,23,34,45,56])
print(arr)
print(arr[2])# fetching the elementas from specifeic index
print(arr[2]+arr[3])# adding elements using the index values

[12 23 34 45 56]
34
79


In [21]:
import numpy as np 
arr= np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr[1,2]) # access the 2d array elements from the index

[[1 2 3]
 [4 5 6]]
6


In [2]:
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[6,7,8]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [6 7 8]]]


In [26]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr[1:4])
print(arr[:6])
print(arr[4:])
print(arr[-4:-1])
print(arr[1:8:2])
print(arr[::2])


[2 3 4]
[1 2 3 4 5 6]
[5 6 7 8 9]
[6 7 8]
[2 4 6 8]
[1 3 5 7 9]


In [27]:
#array iterations
arr = np.array([1,2,3,4,5,6])
for x in arr:
    print(x)

1
2
3
4
5
6


In [29]:
arr1 = np.array([[1,2,3],[12,13,25]])
#print(arr.ndim)

for x in arr1:
    print(x)

[1 2 3]
[12 13 25]


In [30]:
arr1 = np.array([[1,2,3],[5,6,7]])
#print(arr1.ndim)

for x in arr1:
    for y in x:
        print(y)


1
2
3
5
6
7


In [31]:
arr1 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

for i in arr1:
    for j in i:
        for k in j:
            print(k)

1
2
3
4
5
6
7
8
9


In [6]:
#nditer(arr) function
arr3 = np.array([[21,2,33],[4,25,6],[7,84,9]])
print(arr)
print("\n")

for i in np.nditer(arr):
    print(i, sep='')


[1 2 3]


1
2
3


In [9]:
import numpy as np
arr = np.array([1,2,3])

for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [8]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])

for idx, x in np.ndenumerate(arr):
    print(idx,x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [14]:
#Joining Numpy 1D Arrays

arr1 = np.array((1,2,3,4,5))
arr2 = np.array([23,34,45,67])
arr = np.concatenate((arr1,arr2))
print(arr)



[ 1  2  3  4  5 23 34 45 67]


In [11]:
# array is been concatenate
arr1 = np.array([[1,2,3],[3,2,4]])
arr2 = np.array([[21,22,23],[43,32,14]])
arr = np.concatenate((arr1,arr2))
print(arr)

[[ 1  2  3]
 [ 3  2  4]
 [21 22 23]
 [43 32 14]]


In [15]:
#here array is split into 3 different parts
import numpy as np
arr = np.array([10, 29, 37, 64, 15, 56])
arr1 = np.array_split(arr,3)
print(arr1)

[array([10, 29]), array([37, 64]), array([15, 56])]


In [16]:
# find in which which index the given element is present

arr = np.array((1,2,3,4,4,5,6,4))
x = np.where(arr == 4)
print(x)




(array([3, 4, 7], dtype=int64),)


In [19]:
#find where ar
arr = np.array((1,2,3,4,4,5,6,4))
x = np.where(arr%2 == 1)
print(x)

y = np.where(arr%2==0)
print(y)

(array([0, 2, 5], dtype=int64),)
(array([1, 3, 4, 6, 7], dtype=int64),)


In [20]:
#sort the array

import numpy as np
arr = np.array([133, 52, 10,11])
print(np.sort(arr))


[ 10  11  52 133]
