In [2]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
print(np.amin(a))
print(np.amax(a))

1
9


In [4]:
print(np.amin(a,0))
print(np.amax(a,0))

[1 2 3]
[7 8 9]


In [5]:
import numpy as np

arr = np.array([[2,3,4],[22,33,44],[10,20,30]])
print(arr)
print("peak to peak value of array algon axis 0 :", np.ptp(arr,axis=0))
print("peak to peak value of array algon axis 1 :", np.ptp(arr,axis=1))

[[ 2  3  4]
 [22 33 44]
 [10 20 30]]
peak to peak value of array algon axis 0 : [20 30 40]
peak to peak value of array algon axis 1 : [ 2 22 20]


In [6]:
import numpy as np

perc = np.arange(11)
perc = np.percentile(arr,[25,50])
print(arr)
print("\n")
print(perc)


[[ 2  3  4]
 [22 33 44]
 [10 20 30]]


[ 4. 20.]


In [7]:
import numpy as np
arr = np.array([[2,3,4],[22,33,44],[10,20,30]])

print(arr)
print("\n Percentile along the axis 0 :",np.percentile(arr,50,0))
print("\n Percentile along the axis 1 :",np.percentile(arr,50,1))


[[ 2  3  4]
 [22 33 44]
 [10 20 30]]

 Percentile along the axis 0 : [10. 20. 30.]

 Percentile along the axis 1 : [ 3. 33. 20.]


In [8]:
import numpy as np
arr = [20,2,7,1,34]
print("arr :", arr)
print("50th percentile of arr : ",np.percentile(arr,50))
print("25th percentile of arr :", np.percentile(arr,25))
print("75th percentile of arr :", np.percentile(arr,75))

arr : [20, 2, 7, 1, 34]
50th percentile of arr :  7.0
25th percentile of arr : 2.0
75th percentile of arr : 20.0


In [9]:
a = np.array([[3,7,5],[8,4,3],[2,4,9]])

print("array is : \n" , a)
print(np.median(a))
print(np.median(a,axis = 1))
print(np.median(a,axis=0))

array is : 
 [[3 7 5]
 [8 4 3]
 [2 4 9]]
4.0
[5. 4. 4.]
[3. 4. 5.]


In [10]:
a= np.array([[30,17,35],[18,24,33],[12,24,19]])

print(a)

print("the mean is", np.mean(a))
print("the mean function along axis 1", np.mean(a,axis=1))
print("the mean function along axis 0", np.mean(a,axis=0))

[[30 17 35]
 [18 24 33]
 [12 24 19]]
the mean is 23.555555555555557
the mean function along axis 1 [27.33333333 25.         18.33333333]
the mean function along axis 0 [20.         21.66666667 29.        ]


In [11]:
a = np.array([1,2,3,4])
print(a)

print(np.average(a))
wts = np.array([2,3,4,5])
print(np.average(a, weights=wts))
print("\n")



[1 2 3 4]
2.5
2.857142857142857




In [ ]:
import numpy as np
a = np.array([[2,5,7,9,1],[11,33,55,77,22]])
print(arr)
print("Standard deviation of the array is :",np.std(arr))
print("Variance of the array is : ",np.var(arr))
print(np.var(arr))

In [ ]:
#use to reshape the array

import numpy as np
arr = np.arange(12)
print("\n Original array is :\n",arr)
print("\n New array :\n",np.reshape(arr,(3,-1)))

In [22]:
#floor
arr = np.array([12.1, 23.4, 43.3, 55.5, 45.7])
print(arr)
print(np.floor(arr))

[12.1 23.4 43.3 55.5 45.7]
[12. 23. 43. 55. 45.]


In [23]:
#ceil
arr = np.array([12.1, 23.4, 43.3, 55.5, 45.7])
print(arr)
print(np.ceil(arr))

[12.1 23.4 43.3 55.5 45.7]
[13. 24. 44. 56. 46.]


In [24]:
#roundoff
arr = np.array([12.1, 23.4, 43.3, 55.5, 45.7])
print(arr)
print(np.round(arr))

[12.1 23.4 43.3 55.5 45.7]
[12. 23. 43. 56. 46.]


In [ ]:
arr = np.arange(9).reshape(3,3)
print(arr)
